on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: new_app
  AZURE_WEBAPP_PACKAGE_PATH: './node-project/new_app'
  NODE_VERSION: '18.18.0'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Print current working directory
      run: pwd

    - name: List files in the working directory
      run: ls -R

    - name: Install dependencies
      run: npm install
      working-directory: ./node-project/new_app

    - name: Verify node-project directory
      run: ls -R ./node-project

    - name: Verify new_app directory
      run: ls -R ./node-project/new_app || echo "Directory ./node-project/new_app does not exist."

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ./node-project/new_app

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: none
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: Deploy to Azure WebApp
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
